// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/80060c94ef549c077a011977c2b5461bd0fd8947/window-size/index.d.ts
declare module "window-size" {
    /** Height of the terminal window.*/
    export const height: number;

    /** Width of the terminal window.*/
    export const width: number;
}
